
[env]
TERM = "alacritty"

[window]
decorations = "none"
startup_mode = "Fullscreen"
dynamic_padding = true

[font]
size = 16

[font.normal]
family = "Comic Mono Nerd Font"

[cursor.style]
shape = "Underline"
blinking = "Always"

# exit
#[[keyboard.bindings]]
#chars = "exit\u000a"
#key = "E"
#mods = "Shift|Command"

## TMUX 
# todo - more shortcuts (https://tmuxcheatsheet.com/)

# split pane horizontally
[[keyboard.bindings]]
chars = "\u0002\""
key = "E"
mods = "Command"

# split pane vertically
[[keyboard.bindings]]
chars = "\u0002%"
key = "D"
mods = "Command"

# pane left
[[keyboard.bindings]]
chars = "\u0002\u001b\u005b\u0044"
key = "ArrowLeft"
mods = "Command"

# pane right
[[keyboard.bindings]]
chars = "\u0002\u001b\u005b\u0043"
key = "ArrowRight"
mods = "Command"

# pane up
[[keyboard.bindings]]
chars = "\u0002\u001b\u005b\u0041"
key = "ArrowUp"
mods = "Command"

# pane down
[[keyboard.bindings]]
chars = "\u0002\u001b\u005b\u0042"
key = "ArrowDown"
mods = "Command"

# new window
[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

# rename window
[[keyboard.bindings]]
chars = "\u0002,"
key = ","
mods = "Command"

# goto window 1
[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

# goto window 2
[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

# goto window 3
[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

# goto window 4
[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

# goto window 5
[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

# goto window 6
[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

# open command prompt
[[keyboard.bindings]]
chars = """
\u0002:
"""
key = ";"
mods = "Command"

# fzf
[[keyboard.bindings]]
chars = "\u0002F"
key = "F"
mods = "Command|Shift"

## VIM

# save
[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

# quit
#[[keyboard.bindings]]
#chars = """
#\u001B:qa
#"""
#key = "Q"
#mods = "Shift|Command"

## DRACULA
[colors]
indexed_colors = []
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#282A36"
foreground = "#F8F8F2"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#282a36"
cursor = "#f8f8f2"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.selection]
text = "CellForeground"
background = "#44475A"

[colors.normal]
black = "#282A36"
red = "#FF5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.bright]
black = "#6272a4"
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92df"
cyan = "#a4ffff"
white = "#ffffff"

[colors.search.matches]
foreground = "#44475a"
background = "#50fa7b"

[colors.search.focused_match]
foreground = "#44475a"
background = "#ffb86c"

[colors.footer_bar]
background = "#282a36"
foreground = "#f8f8f2"

[colors.hints.start]
foreground = "#282a36"
background = "#f1fa8c"

[colors.hints.end]
foreground = "#f1fa8c"
background = "#282a36"

[general]
# alacritty.toml

live_config_reload = true
