# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

transient_prompt:
  template: "> "
  background: transparent
  newline: true
blocks:
- type: prompt
  alignment: left
  segments:
  - leading_diamond: 
    trailing_diamond: 
    template: "{{ .Icon }} "
    foreground: "#F8F8F2"
    background: "#6272a4"
    type: os
    style: diamond
  - properties:
      style: folder
    leading_diamond: <transparent,background></>
    trailing_diamond: 
    foreground: "#282A36"
    background: "#bd93f9"
    type: path
    style: diamond
  - properties:
      branch_icon: ""
      fetch_stash_count: true
      fetch_status: false
      fetch_upstream_icon: true
    leading_diamond: <transparent,background></>
    trailing_diamond: 
    template: " \uf126 ({{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }}) "
    foreground: "#282A36"
    background: "#F1FA8C"
    type: git
    style: diamond
  newline: true
- type: prompt
  alignment: right
  filler: "<#44475A,transparent>-</>"
  segments:
  - leading_diamond: 
    trailing_diamond: <transparent,background></>
    template:  {{.Profile}}{{if .Region}}@{{.Region}}{{end}}
    foreground: "#F8F8F2"
    background: "#ff79c6"
    type: aws
    style: diamond
  - leading_diamond: 
    trailing_diamond: <transparent,background></>
    template: " \ue718 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} "
    foreground: "#F8F8F2"
    background: "#6272A4"
    type: node
    style: diamond
  - leading_diamond: 
    trailing_diamond: <transparent,background></>
    template: " \ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} "
    foreground: "#F8F8F2"
    background: "#6272A4"
    type: python
    style: diamond
  - properties:
      always_enabled: true
      style: austin
    leading_diamond: 
    trailing_diamond: <transparent,background></>
    template: " {{ .FormattedMs }} \uf252 "
    foreground: "#282A36"
    background: "#FFB86C"
    type: executiontime
    style: diamond
  - leading_diamond: 
    trailing_diamond: 
    foreground: "#F8F8F2"
    background: "#6272A4"
    type: time
    style: diamond
- type: prompt
  alignment: left
  segments:
  - properties:
      always_enabled: true
    template: |-
      
      >
    foreground: "#F8F8F2"
    type: status
    style: plain
    foreground_templates:
    - "{{ if gt .Code 0 }}#FF5555{{ end }}"
  newline: true
version: 3
final_space: true
