---
- name: Check if Chocolatey is installed
  ansible.windows.win_stat:
    path: "C:\\ProgramData\\chocolatey\\bin\\choco.exe"
  register: choco_exists

- name: Install Chocolatey
  ansible.windows.win_shell: |
    Set-ExecutionPolicy Bypass -Scope Process -Force
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  when: not choco_exists.stat.exists

- name: Install Chocolatey packages
  ansible.windows.win_shell: choco install {{ item }} -y --no-progress
  loop: "{{ choco_packages }}"
  ignore_errors: true
  changed_when: false
