---
- name: Get the path of the current iTerm2 custom preferences file
  ansible.builtin.shell: |
    defaults read com.googlecode.iterm2 PrefsCustomFolder
  register: custom_prefs_folder
  ignore_errors: true

- name: Set the iTerm2 preferences path
  ansible.builtin.set_fact:
    iterm2_plist_path: "{{ custom_prefs_folder.stdout }}"
  when: custom_prefs_folder.stdout != ""

- name: Copy iTerm2 preferences to path
  ansible.builtin.copy:
    src: "com.googlecode.iterm2.plist"
    dest: "{{ iterm2_plist_path }}"

- name: Set normal font in preferences
  ansible.builtin.replace:
    path: "{{ iterm2_plist_path }}"
    regexp: "NORMAL_FONT"
    replace: "{{ iterm2_font_normal }} {{ iterm2_font_normal_size }}"

- name: Set non-ascii font in preferences
  ansible.builtin.replace:
    path: "{{ iterm2_plist_path }}"
    regexp: "NOASCII_FONT"
    replace: "{{ iterm2_font_noascii }} {{ iterm2_font_noascii_size }}"

- name: Setup iterm2 shell integrations
  ansible.builtin.shell: |
    curl -L https://iterm2.com/shell_integration/install_shell_integration.sh | bash
  become: yes
  become_user: "{{ ansible_user_id }}"
  args:
    creates: "$HOME/.iterm2_shell_integration.zsh"