---
- name: Install Ultimate vimrc
  ansible.builtin.shell: |
    git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
    sh ~/.vim_runtime/install_awesome_vimrc.sh
  become: true
  become_user: "{{ ansible_user_id }}"
  args:
    creates: "$HOME/.vim_runtime"

- name: Install Vim plugins
  ansible.builtin.shell: |
    vim +PlugInstall +qall

