---
- name: Install winget packages
  ansible.windows.win_shell: >
    winget install --id "{{ item }}"
    --accept-package-agreements --accept-source-agreements --silent
  loop: "{{ winget_packages }}"
  ignore_errors: true
  changed_when: false
